import numpy as np
import matplotlib.pyplot as plt

# Read the output file generated by the Fortran program
data = np.loadtxt('verena\week3\heatdiffusion_output.txt')

# Extract temperature values at the first and last time step
temperature_initial = data[0, 1:]
temperature_final = data[1, 1:]

# Define spatial grid
nx = len(temperature_initial)
x = np.linspace(0, 1, nx)

# Plot temperature distribution at the initial and final time step
plt.figure(figsize=(10, 5))
plt.plot(x, temperature_initial, label='Initial time')
plt.plot(x, temperature_final, label='Final time')
plt.xlabel('x')
plt.ylabel('Temperature')
plt.title('Temperature distribution over space')
plt.legend()
plt.grid(True)
plt.show()